/*
 * generated by Xtext
 */
package org.eclipse.recommenders.snipeditor.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.recommenders.snipeditor.ui.internal.SnipDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SnipDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SnipDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SnipDSLActivator.getInstance().getInjector(SnipDSLActivator.ORG_ECLIPSE_RECOMMENDERS_SNIPEDITOR_SNIPDSL);
	}
	
}
