/*
 * generated by Xtext
 */
package org.eclipse.recommenders.templates.rcp;

/**
 * Initialization support for running Xtext languages without equinox extension
 * registry
 */
public class SnipDSLStandaloneSetup extends SnipDSLStandaloneSetupGenerated {

    public static void doSetup() {
        new SnipDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
