/*
 * generated by Xtext
 */
package org.eclipse.recommenders.snipeditor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SnipDSLRuntimeModule extends org.eclipse.recommenders.snipeditor.AbstractSnipDSLRuntimeModule {

}
