/*
* generated by Xtext
*/
package org.eclipse.recommenders.snipeditor;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SnipDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.eclipse.recommenders.snipeditor.ui.internal.SnipDSLActivator.getInstance().getInjector("org.eclipse.recommenders.snipeditor.SnipDSL");
	}
	
}
