/**
 * generated by Xtext
 */
package org.eclipse.recommenders.snipeditor.validation;

import org.eclipse.recommenders.snipeditor.validation.AbstractSnipDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SnipDSLValidator extends AbstractSnipDSLValidator {
}
