/*
 * generated by Xtext
 */
package org.eclipse.recommenders.templates.rcp.contentassist

import org.eclipse.recommenders.templates.rcp.contentassist.AbstractSnipDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SnipDSLProposalProvider extends AbstractSnipDSLProposalProvider {
}
