/*
 * generated by Xtext
 */
package org.eclipse.recommenders.templates.rcp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SnipDSLUiModule extends
        org.eclipse.recommenders.templates.rcp.ui.AbstractSnipDSLUiModule {
    public SnipDSLUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
