/*
 * generated by Xtext
 */
package org.eclipse.recommenders.snipeditor.ui;

import org.eclipse.recommenders.snipeditor.ui.contentassist.SnipDSLReferenceProposalCreator;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SnipDSLUiModule extends org.eclipse.recommenders.snipeditor.ui.AbstractSnipDSLUiModule {
	public SnipDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.ReferenceProposalCreator> bindAbstractJavaBasedContentProposalProvider$ReferenceProposalCreator() {
		return SnipDSLReferenceProposalCreator.class;
	}
}
