/*
 * generated by Xtext
 */
package org.eclipse.recommenders.snipeditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SnipDSLUiModule extends org.eclipse.recommenders.snipeditor.ui.AbstractSnipDSLUiModule {
	public SnipDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
