/**
 * generated by Xtext
 */
package org.eclipse.recommenders.snipeditor.ui.contentassist;

import org.eclipse.recommenders.snipeditor.ui.contentassist.AbstractSnipDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SnipDSLProposalProvider extends AbstractSnipDSLProposalProvider {
}
