/*
* generated by Xtext
*/
package org.eclipse.recommenders.snipeditor.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.recommenders.snipeditor.services.SnipDSLGrammarAccess;

public class SnipDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SnipDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.recommenders.snipeditor.parser.antlr.internal.InternalSnipDSLParser createParser(XtextTokenStream stream) {
		return new org.eclipse.recommenders.snipeditor.parser.antlr.internal.InternalSnipDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "domainmodel";
	}
	
	public SnipDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SnipDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
