/*
* generated by Xtext
*/
package org.eclipse.recommenders.snipeditor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SnipDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/recommenders/snipeditor/parser/antlr/internal/InternalSnipDSL.tokens");
	}
}
